title: Aniket Lokhande
#logo: /assets/img/headshot_circle.png
description: Hey there! I'm Aniket, a data analyst skilled in Power BI, SQL, and Python, specializing in data visualization and insights. I've built 300+ dashboards and worked with complex datasets, turning raw data into impactful decisions. 🚀
show_downloads: false
theme: jekyll-theme-cayman
